### ISSUE TITLE
Plugin Update?

### ISSUE THREAD

**Issue by pburtchaell** [ThatRendle/brackets-grunt#8]
Is this plugin still being maintained? Just curious.

**Comment by custa1200** [comment]
Also would like to know the status of this plugin? Looking to start usingBrackets for coding and this would be a great help.

**Comment by mackelito** [comment]
+1

**Comment by christianrondeau** [comment]
Same thing here. I'm thinking of starting a similar project in the future, but I would prefer contribute to an existing one if there's still planned activity.

**Comment by pburtchaell** [comment]
Closing.
